name: "jackal"
N: 20
integrator_step: 0.2
n_discs: 1

solver_settings:
  solver: "acados" # acados or forces
  # solver: "forces" # acados or forces
  acados:
    iterations: 2 #2 # 1
    solver_type: SQP_RTI # SQP_RTI (default) or SQP
  forces:
    use_sqp: false

control_frequency: 30
max_obstacles: 8
obstacle_radius: 0.4
braking_velocity: 1.0

contouring:
  num_segments: 3

weights:
  goal: 5.
  velocity: 0.02
  acceleration: 0.05
  rotational_velocity: 2. #0.05

reference_velocity: 0.5
