name: "Jetracer"
N: 20
integrator_step: 0.2
n_discs: 0
track_choice: "sinus" # 'straight_line', sinus
start_x: -5.0

verbose: false
debug_visuals: true

solver_settings:
  iterations: 1 #2 # 1
  solver_type: SQP_RTI # SQP_RTI (default) or SQP

control_frequency: 20
max_obstacles: 8
obstacle_radius: 0.5
robot_radius: 0.325
robot:
  length: 0.65
  width: 0.65
  com_to_back: 0.0
braking_acceleration: 1.0

contouring:
  num_segments: 5
  use_huber: false

decomp:
  max_constraints: 16

weights:
  goal: 2.
  throttle: .05
  steering: .05
  velocity: 1.
  reference_velocity: 1.
  reference_steering: 2.
  lag: 0.1
  contour: 0.05
  terminal_angle: 5.0 # 0.0
  terminal_contour: 1.0 # 0.0
  terminal_lag: 1.0 # 0.0






