name: "Jetracer"
N: 10
integrator_step: 0.1
n_discs: 0

verbose: false
debug_visuals: true

solver_settings:
  iterations: 6 #2 # 1
  solver_type: SQP_RTI # SQP_RTI (default) or SQP

control_frequency: 20
max_obstacles: 8
obstacle_radius: 0.5
robot_radius: 0.325
braking_acceleration: 1.0

contouring:
  num_segments: 5
  use_huber: false

decomp:
  max_constraints: 16

weights:
  goal: 2.
  throttle: .05
  steering: 1.
  velocity: 1.
  reference_velocity: 4.
  reference_steering: 2.





