/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Solver_expl_ode_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[59] = {7, 7, 0, 7, 14, 21, 28, 35, 42, 49, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s2[27] = {7, 3, 0, 7, 14, 21, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s3[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s4[26] = {22, 1, 0, 22, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21};
static const casadi_int casadi_s5[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s6[59] = {55, 1, 0, 55, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54};

/* Solver_expl_ode_hess:(i0[7],i1[7x7],i2[7x3],i3[7],i4[3],i5[22])->(o0[10],o1[55]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a3=arg[0]? arg[0][3] : 0;
  a4=arg[3]? arg[3][1] : 0;
  a5=(a3*a4);
  a6=(a2*a5);
  a7=sin(a1);
  a8=9.4500000000000001e-02;
  a9=3.8302866000000002e-01;
  a10=-1.2053807000000001e+00;
  a11=arg[4]? arg[4][1] : 0;
  a12=8.7391860000000002e-02;
  a11=(a11-a12);
  a11=(a10*a11);
  a11=tanh(a11);
  a12=(a9*a11);
  a13=tan(a12);
  a14=(a3*a13);
  a15=1.7499999999999999e-01;
  a14=(a14/a15);
  a14=(a8*a14);
  a15=(a14*a4);
  a16=(a7*a15);
  a6=(a6-a16);
  a16=cos(a1);
  a17=arg[3]? arg[3][0] : 0;
  a14=(a14*a17);
  a18=(a16*a14);
  a6=(a6-a18);
  a18=sin(a1);
  a19=(a3*a17);
  a20=(a18*a19);
  a6=(a6-a20);
  if (res[0]!=0) res[0][2]=a6;
  a6=arg[3]? arg[3][6] : 0;
  a20=2.8984865546226501e-01;
  a21=5.9666561772851068e-01;
  a22=arg[3]? arg[3][3] : 0;
  a21=(a21*a22);
  a20=(a20*a21);
  a6=(a6-a20);
  a20=1.3312559127807617e+01;
  a22=1.;
  a23=(a20*a3);
  a23=tanh(a23);
  a24=casadi_sq(a23);
  a24=(a22-a24);
  a25=-1.7194761037826538e+00;
  a25=(a25*a21);
  a24=(a24*a25);
  a24=(a20*a24);
  a6=(a6+a24);
  a24=5.9861721992492676e+00;
  a26=5.0000000000000000e-01;
  a27=100.;
  a28=arg[4]? arg[4][2] : 0;
  a29=-1.5045104920864105e-01;
  a30=(a28+a29);
  a30=(a27*a30);
  a30=tanh(a30);
  a31=(a30+a22);
  a31=(a26*a31);
  a28=(a28+a29);
  a28=(a28*a21);
  a29=(a31*a28);
  a29=(a24*a29);
  a6=(a6-a29);
  a29=sin(a1);
  a29=(a29*a4);
  a6=(a6+a29);
  a29=5.7142857142857144e+00;
  a32=arg[3]? arg[3][2] : 0;
  a33=cos(a1);
  a33=(a33*a4);
  a34=sin(a1);
  a34=(a34*a17);
  a33=(a33-a34);
  a33=(a8*a33);
  a32=(a32+a33);
  a32=(a29*a32);
  a33=(a13*a32);
  a6=(a6+a33);
  a33=cos(a1);
  a33=(a33*a17);
  a6=(a6+a33);
  if (res[0]!=0) res[0][3]=a6;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  a0=casadi_sq(a11);
  a0=(a22-a0);
  a6=(a3*a32);
  a33=cos(a12);
  a34=casadi_sq(a33);
  a6=(a6/a34);
  a35=(a9*a6);
  a36=(a0*a35);
  a36=(a10*a36);
  if (res[0]!=0) res[0][8]=a36;
  a36=2.8887779235839844e+01;
  a37=(a24*a3);
  a36=(a36-a37);
  a37=(a36*a31);
  a37=(a37*a21);
  a38=casadi_sq(a30);
  a38=(a22-a38);
  a39=(a36*a28);
  a39=(a26*a39);
  a40=(a38*a39);
  a40=(a27*a40);
  a37=(a37+a40);
  if (res[0]!=0) res[0][9]=a37;
  a37=arg[1]? arg[1][2] : 0;
  a40=arg[1]? arg[1][3] : 0;
  a41=(a4*a40);
  a41=(a2*a41);
  a42=sin(a1);
  a43=(a42*a37);
  a43=(a5*a43);
  a41=(a41-a43);
  a43=cos(a1);
  a44=(a43*a37);
  a44=(a15*a44);
  a45=(a13*a40);
  a45=(a29*a45);
  a45=(a8*a45);
  a46=(a4*a45);
  a46=(a7*a46);
  a44=(a44+a46);
  a41=(a41-a44);
  a45=(a17*a45);
  a45=(a16*a45);
  a44=sin(a1);
  a46=(a44*a37);
  a46=(a14*a46);
  a45=(a45-a46);
  a41=(a41-a45);
  a45=cos(a1);
  a46=(a45*a37);
  a46=(a19*a46);
  a47=(a17*a40);
  a47=(a18*a47);
  a46=(a46+a47);
  a41=(a41-a46);
  a46=(a37*a41);
  a47=cos(a1);
  a48=(a47*a37);
  a48=(a4*a48);
  a49=(a23+a23);
  a23=casadi_sq(a23);
  a23=(a22-a23);
  a50=(a20*a40);
  a50=(a23*a50);
  a50=(a49*a50);
  a50=(a25*a50);
  a50=(a20*a50);
  a48=(a48-a50);
  a50=sin(a1);
  a51=(a50*a37);
  a51=(a4*a51);
  a52=cos(a1);
  a53=(a52*a37);
  a53=(a17*a53);
  a51=(a51+a53);
  a51=(a8*a51);
  a51=(a29*a51);
  a53=(a13*a51);
  a48=(a48-a53);
  a1=sin(a1);
  a37=(a1*a37);
  a37=(a17*a37);
  a48=(a48-a37);
  a37=(a40*a48);
  a46=(a46+a37);
  if (res[1]!=0) res[1][0]=a46;
  a46=arg[1]? arg[1][9] : 0;
  a37=(a46*a41);
  a53=arg[1]? arg[1][10] : 0;
  a54=(a53*a48);
  a37=(a37+a54);
  if (res[1]!=0) res[1][1]=a37;
  a37=arg[1]? arg[1][16] : 0;
  a54=(a37*a41);
  a55=arg[1]? arg[1][17] : 0;
  a56=(a55*a48);
  a54=(a54+a56);
  if (res[1]!=0) res[1][2]=a54;
  a54=arg[1]? arg[1][23] : 0;
  a56=(a54*a41);
  a57=arg[1]? arg[1][24] : 0;
  a58=(a57*a48);
  a56=(a56+a58);
  if (res[1]!=0) res[1][3]=a56;
  a56=arg[1]? arg[1][30] : 0;
  a58=(a56*a41);
  a59=arg[1]? arg[1][31] : 0;
  a60=(a59*a48);
  a58=(a58+a60);
  if (res[1]!=0) res[1][4]=a58;
  a58=arg[1]? arg[1][37] : 0;
  a60=(a58*a41);
  a61=arg[1]? arg[1][38] : 0;
  a62=(a61*a48);
  a60=(a60+a62);
  if (res[1]!=0) res[1][5]=a60;
  a60=arg[1]? arg[1][44] : 0;
  a62=(a60*a41);
  a63=arg[1]? arg[1][45] : 0;
  a64=(a63*a48);
  a62=(a62+a64);
  if (res[1]!=0) res[1][6]=a62;
  a62=arg[2]? arg[2][2] : 0;
  a64=(a62*a41);
  a65=arg[2]? arg[2][3] : 0;
  a66=(a65*a48);
  a64=(a64+a66);
  if (res[1]!=0) res[1][7]=a64;
  a64=arg[2]? arg[2][9] : 0;
  a66=(a64*a41);
  a67=arg[2]? arg[2][10] : 0;
  a68=(a67*a48);
  a66=(a66+a68);
  a68=(a32*a40);
  a51=(a3*a51);
  a68=(a68-a51);
  a68=(a68/a34);
  a68=(a9*a68);
  a68=(a0*a68);
  a68=(a10*a68);
  a66=(a66+a68);
  if (res[1]!=0) res[1][8]=a66;
  a66=arg[2]? arg[2][16] : 0;
  a41=(a66*a41);
  a68=arg[2]? arg[2][17] : 0;
  a48=(a68*a48);
  a41=(a41+a48);
  a40=(a24*a40);
  a48=(a31*a40);
  a48=(a21*a48);
  a40=(a28*a40);
  a40=(a26*a40);
  a40=(a38*a40);
  a40=(a27*a40);
  a48=(a48+a40);
  a41=(a41-a48);
  if (res[1]!=0) res[1][9]=a41;
  a41=(a4*a53);
  a41=(a2*a41);
  a48=(a42*a46);
  a48=(a5*a48);
  a41=(a41-a48);
  a48=(a43*a46);
  a48=(a15*a48);
  a40=(a13*a53);
  a40=(a29*a40);
  a40=(a8*a40);
  a51=(a4*a40);
  a51=(a7*a51);
  a48=(a48+a51);
  a41=(a41-a48);
  a40=(a17*a40);
  a40=(a16*a40);
  a48=(a44*a46);
  a48=(a14*a48);
  a40=(a40-a48);
  a41=(a41-a40);
  a40=(a45*a46);
  a40=(a19*a40);
  a48=(a17*a53);
  a48=(a18*a48);
  a40=(a40+a48);
  a41=(a41-a40);
  a40=(a46*a41);
  a48=(a47*a46);
  a48=(a4*a48);
  a51=(a20*a53);
  a51=(a23*a51);
  a51=(a49*a51);
  a51=(a25*a51);
  a51=(a20*a51);
  a48=(a48-a51);
  a51=(a50*a46);
  a51=(a4*a51);
  a69=(a52*a46);
  a69=(a17*a69);
  a51=(a51+a69);
  a51=(a8*a51);
  a51=(a29*a51);
  a69=(a13*a51);
  a48=(a48-a69);
  a46=(a1*a46);
  a46=(a17*a46);
  a48=(a48-a46);
  a46=(a53*a48);
  a40=(a40+a46);
  if (res[1]!=0) res[1][10]=a40;
  a40=(a37*a41);
  a46=(a55*a48);
  a40=(a40+a46);
  if (res[1]!=0) res[1][11]=a40;
  a40=(a54*a41);
  a46=(a57*a48);
  a40=(a40+a46);
  if (res[1]!=0) res[1][12]=a40;
  a40=(a56*a41);
  a46=(a59*a48);
  a40=(a40+a46);
  if (res[1]!=0) res[1][13]=a40;
  a40=(a58*a41);
  a46=(a61*a48);
  a40=(a40+a46);
  if (res[1]!=0) res[1][14]=a40;
  a40=(a60*a41);
  a46=(a63*a48);
  a40=(a40+a46);
  if (res[1]!=0) res[1][15]=a40;
  a40=(a62*a41);
  a46=(a65*a48);
  a40=(a40+a46);
  if (res[1]!=0) res[1][16]=a40;
  a40=(a64*a41);
  a46=(a67*a48);
  a40=(a40+a46);
  a46=(a32*a53);
  a51=(a3*a51);
  a46=(a46-a51);
  a46=(a46/a34);
  a46=(a9*a46);
  a46=(a0*a46);
  a46=(a10*a46);
  a40=(a40+a46);
  if (res[1]!=0) res[1][17]=a40;
  a41=(a66*a41);
  a48=(a68*a48);
  a41=(a41+a48);
  a53=(a24*a53);
  a48=(a31*a53);
  a48=(a21*a48);
  a53=(a28*a53);
  a53=(a26*a53);
  a53=(a38*a53);
  a53=(a27*a53);
  a48=(a48+a53);
  a41=(a41-a48);
  if (res[1]!=0) res[1][18]=a41;
  a41=(a4*a55);
  a41=(a2*a41);
  a48=(a42*a37);
  a48=(a5*a48);
  a41=(a41-a48);
  a48=(a43*a37);
  a48=(a15*a48);
  a53=(a13*a55);
  a53=(a29*a53);
  a53=(a8*a53);
  a40=(a4*a53);
  a40=(a7*a40);
  a48=(a48+a40);
  a41=(a41-a48);
  a53=(a17*a53);
  a53=(a16*a53);
  a48=(a44*a37);
  a48=(a14*a48);
  a53=(a53-a48);
  a41=(a41-a53);
  a53=(a45*a37);
  a53=(a19*a53);
  a48=(a17*a55);
  a48=(a18*a48);
  a53=(a53+a48);
  a41=(a41-a53);
  a53=(a37*a41);
  a48=(a47*a37);
  a48=(a4*a48);
  a40=(a20*a55);
  a40=(a23*a40);
  a40=(a49*a40);
  a40=(a25*a40);
  a40=(a20*a40);
  a48=(a48-a40);
  a40=(a50*a37);
  a40=(a4*a40);
  a46=(a52*a37);
  a46=(a17*a46);
  a40=(a40+a46);
  a40=(a8*a40);
  a40=(a29*a40);
  a46=(a13*a40);
  a48=(a48-a46);
  a37=(a1*a37);
  a37=(a17*a37);
  a48=(a48-a37);
  a37=(a55*a48);
  a53=(a53+a37);
  if (res[1]!=0) res[1][19]=a53;
  a53=(a54*a41);
  a37=(a57*a48);
  a53=(a53+a37);
  if (res[1]!=0) res[1][20]=a53;
  a53=(a56*a41);
  a37=(a59*a48);
  a53=(a53+a37);
  if (res[1]!=0) res[1][21]=a53;
  a53=(a58*a41);
  a37=(a61*a48);
  a53=(a53+a37);
  if (res[1]!=0) res[1][22]=a53;
  a53=(a60*a41);
  a37=(a63*a48);
  a53=(a53+a37);
  if (res[1]!=0) res[1][23]=a53;
  a53=(a62*a41);
  a37=(a65*a48);
  a53=(a53+a37);
  if (res[1]!=0) res[1][24]=a53;
  a53=(a64*a41);
  a37=(a67*a48);
  a53=(a53+a37);
  a37=(a32*a55);
  a40=(a3*a40);
  a37=(a37-a40);
  a37=(a37/a34);
  a37=(a9*a37);
  a37=(a0*a37);
  a37=(a10*a37);
  a53=(a53+a37);
  if (res[1]!=0) res[1][25]=a53;
  a41=(a66*a41);
  a48=(a68*a48);
  a41=(a41+a48);
  a55=(a24*a55);
  a48=(a31*a55);
  a48=(a21*a48);
  a55=(a28*a55);
  a55=(a26*a55);
  a55=(a38*a55);
  a55=(a27*a55);
  a48=(a48+a55);
  a41=(a41-a48);
  if (res[1]!=0) res[1][26]=a41;
  a41=(a4*a57);
  a41=(a2*a41);
  a48=(a42*a54);
  a48=(a5*a48);
  a41=(a41-a48);
  a48=(a43*a54);
  a48=(a15*a48);
  a55=(a13*a57);
  a55=(a29*a55);
  a55=(a8*a55);
  a53=(a4*a55);
  a53=(a7*a53);
  a48=(a48+a53);
  a41=(a41-a48);
  a55=(a17*a55);
  a55=(a16*a55);
  a48=(a44*a54);
  a48=(a14*a48);
  a55=(a55-a48);
  a41=(a41-a55);
  a55=(a45*a54);
  a55=(a19*a55);
  a48=(a17*a57);
  a48=(a18*a48);
  a55=(a55+a48);
  a41=(a41-a55);
  a55=(a54*a41);
  a48=(a47*a54);
  a48=(a4*a48);
  a53=(a20*a57);
  a53=(a23*a53);
  a53=(a49*a53);
  a53=(a25*a53);
  a53=(a20*a53);
  a48=(a48-a53);
  a53=(a50*a54);
  a53=(a4*a53);
  a37=(a52*a54);
  a37=(a17*a37);
  a53=(a53+a37);
  a53=(a8*a53);
  a53=(a29*a53);
  a37=(a13*a53);
  a48=(a48-a37);
  a54=(a1*a54);
  a54=(a17*a54);
  a48=(a48-a54);
  a54=(a57*a48);
  a55=(a55+a54);
  if (res[1]!=0) res[1][27]=a55;
  a55=(a56*a41);
  a54=(a59*a48);
  a55=(a55+a54);
  if (res[1]!=0) res[1][28]=a55;
  a55=(a58*a41);
  a54=(a61*a48);
  a55=(a55+a54);
  if (res[1]!=0) res[1][29]=a55;
  a55=(a60*a41);
  a54=(a63*a48);
  a55=(a55+a54);
  if (res[1]!=0) res[1][30]=a55;
  a55=(a62*a41);
  a54=(a65*a48);
  a55=(a55+a54);
  if (res[1]!=0) res[1][31]=a55;
  a55=(a64*a41);
  a54=(a67*a48);
  a55=(a55+a54);
  a54=(a32*a57);
  a53=(a3*a53);
  a54=(a54-a53);
  a54=(a54/a34);
  a54=(a9*a54);
  a54=(a0*a54);
  a54=(a10*a54);
  a55=(a55+a54);
  if (res[1]!=0) res[1][32]=a55;
  a41=(a66*a41);
  a48=(a68*a48);
  a41=(a41+a48);
  a57=(a24*a57);
  a48=(a31*a57);
  a48=(a21*a48);
  a57=(a28*a57);
  a57=(a26*a57);
  a57=(a38*a57);
  a57=(a27*a57);
  a48=(a48+a57);
  a41=(a41-a48);
  if (res[1]!=0) res[1][33]=a41;
  a41=(a4*a59);
  a41=(a2*a41);
  a48=(a42*a56);
  a48=(a5*a48);
  a41=(a41-a48);
  a48=(a43*a56);
  a48=(a15*a48);
  a57=(a13*a59);
  a57=(a29*a57);
  a57=(a8*a57);
  a55=(a4*a57);
  a55=(a7*a55);
  a48=(a48+a55);
  a41=(a41-a48);
  a57=(a17*a57);
  a57=(a16*a57);
  a48=(a44*a56);
  a48=(a14*a48);
  a57=(a57-a48);
  a41=(a41-a57);
  a57=(a45*a56);
  a57=(a19*a57);
  a48=(a17*a59);
  a48=(a18*a48);
  a57=(a57+a48);
  a41=(a41-a57);
  a57=(a56*a41);
  a48=(a47*a56);
  a48=(a4*a48);
  a55=(a20*a59);
  a55=(a23*a55);
  a55=(a49*a55);
  a55=(a25*a55);
  a55=(a20*a55);
  a48=(a48-a55);
  a55=(a50*a56);
  a55=(a4*a55);
  a54=(a52*a56);
  a54=(a17*a54);
  a55=(a55+a54);
  a55=(a8*a55);
  a55=(a29*a55);
  a54=(a13*a55);
  a48=(a48-a54);
  a56=(a1*a56);
  a56=(a17*a56);
  a48=(a48-a56);
  a56=(a59*a48);
  a57=(a57+a56);
  if (res[1]!=0) res[1][34]=a57;
  a57=(a58*a41);
  a56=(a61*a48);
  a57=(a57+a56);
  if (res[1]!=0) res[1][35]=a57;
  a57=(a60*a41);
  a56=(a63*a48);
  a57=(a57+a56);
  if (res[1]!=0) res[1][36]=a57;
  a57=(a62*a41);
  a56=(a65*a48);
  a57=(a57+a56);
  if (res[1]!=0) res[1][37]=a57;
  a57=(a64*a41);
  a56=(a67*a48);
  a57=(a57+a56);
  a56=(a32*a59);
  a55=(a3*a55);
  a56=(a56-a55);
  a56=(a56/a34);
  a56=(a9*a56);
  a56=(a0*a56);
  a56=(a10*a56);
  a57=(a57+a56);
  if (res[1]!=0) res[1][38]=a57;
  a41=(a66*a41);
  a48=(a68*a48);
  a41=(a41+a48);
  a59=(a24*a59);
  a48=(a31*a59);
  a48=(a21*a48);
  a59=(a28*a59);
  a59=(a26*a59);
  a59=(a38*a59);
  a59=(a27*a59);
  a48=(a48+a59);
  a41=(a41-a48);
  if (res[1]!=0) res[1][39]=a41;
  a41=(a4*a61);
  a41=(a2*a41);
  a48=(a42*a58);
  a48=(a5*a48);
  a41=(a41-a48);
  a48=(a43*a58);
  a48=(a15*a48);
  a59=(a13*a61);
  a59=(a29*a59);
  a59=(a8*a59);
  a57=(a4*a59);
  a57=(a7*a57);
  a48=(a48+a57);
  a41=(a41-a48);
  a59=(a17*a59);
  a59=(a16*a59);
  a48=(a44*a58);
  a48=(a14*a48);
  a59=(a59-a48);
  a41=(a41-a59);
  a59=(a45*a58);
  a59=(a19*a59);
  a48=(a17*a61);
  a48=(a18*a48);
  a59=(a59+a48);
  a41=(a41-a59);
  a59=(a58*a41);
  a48=(a47*a58);
  a48=(a4*a48);
  a57=(a20*a61);
  a57=(a23*a57);
  a57=(a49*a57);
  a57=(a25*a57);
  a57=(a20*a57);
  a48=(a48-a57);
  a57=(a50*a58);
  a57=(a4*a57);
  a56=(a52*a58);
  a56=(a17*a56);
  a57=(a57+a56);
  a57=(a8*a57);
  a57=(a29*a57);
  a56=(a13*a57);
  a48=(a48-a56);
  a58=(a1*a58);
  a58=(a17*a58);
  a48=(a48-a58);
  a58=(a61*a48);
  a59=(a59+a58);
  if (res[1]!=0) res[1][40]=a59;
  a59=(a60*a41);
  a58=(a63*a48);
  a59=(a59+a58);
  if (res[1]!=0) res[1][41]=a59;
  a59=(a62*a41);
  a58=(a65*a48);
  a59=(a59+a58);
  if (res[1]!=0) res[1][42]=a59;
  a59=(a64*a41);
  a58=(a67*a48);
  a59=(a59+a58);
  a58=(a32*a61);
  a57=(a3*a57);
  a58=(a58-a57);
  a58=(a58/a34);
  a58=(a9*a58);
  a58=(a0*a58);
  a58=(a10*a58);
  a59=(a59+a58);
  if (res[1]!=0) res[1][43]=a59;
  a41=(a66*a41);
  a48=(a68*a48);
  a41=(a41+a48);
  a61=(a24*a61);
  a48=(a31*a61);
  a48=(a21*a48);
  a61=(a28*a61);
  a61=(a26*a61);
  a61=(a38*a61);
  a61=(a27*a61);
  a48=(a48+a61);
  a41=(a41-a48);
  if (res[1]!=0) res[1][44]=a41;
  a41=(a4*a63);
  a41=(a2*a41);
  a48=(a42*a60);
  a48=(a5*a48);
  a41=(a41-a48);
  a48=(a43*a60);
  a48=(a15*a48);
  a61=(a13*a63);
  a61=(a29*a61);
  a61=(a8*a61);
  a59=(a4*a61);
  a59=(a7*a59);
  a48=(a48+a59);
  a41=(a41-a48);
  a61=(a17*a61);
  a61=(a16*a61);
  a48=(a44*a60);
  a48=(a14*a48);
  a61=(a61-a48);
  a41=(a41-a61);
  a61=(a45*a60);
  a61=(a19*a61);
  a48=(a17*a63);
  a48=(a18*a48);
  a61=(a61+a48);
  a41=(a41-a61);
  a61=(a60*a41);
  a48=(a47*a60);
  a48=(a4*a48);
  a59=(a20*a63);
  a59=(a23*a59);
  a59=(a49*a59);
  a59=(a25*a59);
  a59=(a20*a59);
  a48=(a48-a59);
  a59=(a50*a60);
  a59=(a4*a59);
  a58=(a52*a60);
  a58=(a17*a58);
  a59=(a59+a58);
  a59=(a8*a59);
  a59=(a29*a59);
  a58=(a13*a59);
  a48=(a48-a58);
  a60=(a1*a60);
  a60=(a17*a60);
  a48=(a48-a60);
  a60=(a63*a48);
  a61=(a61+a60);
  if (res[1]!=0) res[1][45]=a61;
  a61=(a62*a41);
  a60=(a65*a48);
  a61=(a61+a60);
  if (res[1]!=0) res[1][46]=a61;
  a61=(a64*a41);
  a60=(a67*a48);
  a61=(a61+a60);
  a60=(a32*a63);
  a59=(a3*a59);
  a60=(a60-a59);
  a60=(a60/a34);
  a60=(a9*a60);
  a60=(a0*a60);
  a60=(a10*a60);
  a61=(a61+a60);
  if (res[1]!=0) res[1][47]=a61;
  a41=(a66*a41);
  a48=(a68*a48);
  a41=(a41+a48);
  a63=(a24*a63);
  a48=(a31*a63);
  a48=(a21*a48);
  a63=(a28*a63);
  a63=(a26*a63);
  a63=(a38*a63);
  a63=(a27*a63);
  a48=(a48+a63);
  a41=(a41-a48);
  if (res[1]!=0) res[1][48]=a41;
  a41=(a4*a65);
  a41=(a2*a41);
  a48=(a42*a62);
  a48=(a5*a48);
  a41=(a41-a48);
  a48=(a43*a62);
  a48=(a15*a48);
  a63=(a13*a65);
  a63=(a29*a63);
  a63=(a8*a63);
  a61=(a4*a63);
  a61=(a7*a61);
  a48=(a48+a61);
  a41=(a41-a48);
  a63=(a17*a63);
  a63=(a16*a63);
  a48=(a44*a62);
  a48=(a14*a48);
  a63=(a63-a48);
  a41=(a41-a63);
  a63=(a45*a62);
  a63=(a19*a63);
  a48=(a17*a65);
  a48=(a18*a48);
  a63=(a63+a48);
  a41=(a41-a63);
  a63=(a62*a41);
  a48=(a47*a62);
  a48=(a4*a48);
  a61=(a20*a65);
  a61=(a23*a61);
  a61=(a49*a61);
  a61=(a25*a61);
  a61=(a20*a61);
  a48=(a48-a61);
  a61=(a50*a62);
  a61=(a4*a61);
  a60=(a52*a62);
  a60=(a17*a60);
  a61=(a61+a60);
  a61=(a8*a61);
  a61=(a29*a61);
  a60=(a13*a61);
  a48=(a48-a60);
  a62=(a1*a62);
  a62=(a17*a62);
  a48=(a48-a62);
  a62=(a65*a48);
  a63=(a63+a62);
  if (res[1]!=0) res[1][49]=a63;
  a63=(a64*a41);
  a62=(a67*a48);
  a63=(a63+a62);
  a62=(a32*a65);
  a61=(a3*a61);
  a62=(a62-a61);
  a62=(a62/a34);
  a62=(a9*a62);
  a62=(a0*a62);
  a62=(a10*a62);
  a63=(a63+a62);
  if (res[1]!=0) res[1][50]=a63;
  a41=(a66*a41);
  a48=(a68*a48);
  a41=(a41+a48);
  a65=(a24*a65);
  a48=(a31*a65);
  a48=(a21*a48);
  a65=(a28*a65);
  a65=(a26*a65);
  a65=(a38*a65);
  a65=(a27*a65);
  a48=(a48+a65);
  a41=(a41-a48);
  if (res[1]!=0) res[1][51]=a41;
  a41=(a4*a67);
  a41=(a2*a41);
  a48=(a42*a64);
  a48=(a5*a48);
  a41=(a41-a48);
  a48=(a43*a64);
  a48=(a15*a48);
  a65=(a13*a67);
  a63=casadi_sq(a11);
  a63=(a22-a63);
  a63=(a10*a63);
  a62=(a9*a63);
  a61=cos(a12);
  a61=casadi_sq(a61);
  a61=(a62/a61);
  a60=(a3*a61);
  a65=(a65+a60);
  a65=(a29*a65);
  a65=(a8*a65);
  a60=(a4*a65);
  a60=(a7*a60);
  a48=(a48+a60);
  a41=(a41-a48);
  a65=(a17*a65);
  a65=(a16*a65);
  a48=(a44*a64);
  a48=(a14*a48);
  a65=(a65-a48);
  a41=(a41-a65);
  a65=(a45*a64);
  a65=(a19*a65);
  a48=(a17*a67);
  a48=(a18*a48);
  a65=(a65+a48);
  a41=(a41-a65);
  a65=(a64*a41);
  a48=(a47*a64);
  a48=(a4*a48);
  a60=(a20*a67);
  a60=(a23*a60);
  a60=(a49*a60);
  a60=(a25*a60);
  a60=(a20*a60);
  a48=(a48-a60);
  a61=(a32*a61);
  a60=(a50*a64);
  a60=(a4*a60);
  a59=(a52*a64);
  a59=(a17*a59);
  a60=(a60+a59);
  a60=(a8*a60);
  a60=(a29*a60);
  a59=(a13*a60);
  a61=(a61-a59);
  a48=(a48+a61);
  a64=(a1*a64);
  a64=(a17*a64);
  a48=(a48-a64);
  a64=(a67*a48);
  a65=(a65+a64);
  a32=(a32*a67);
  a3=(a3*a60);
  a32=(a32-a3);
  a32=(a32/a34);
  a6=(a6/a34);
  a33=(a33+a33);
  a12=sin(a12);
  a12=(a12*a62);
  a33=(a33*a12);
  a6=(a6*a33);
  a32=(a32+a6);
  a9=(a9*a32);
  a0=(a0*a9);
  a11=(a11+a11);
  a11=(a11*a63);
  a35=(a35*a11);
  a0=(a0-a35);
  a10=(a10*a0);
  a65=(a65+a10);
  if (res[1]!=0) res[1][52]=a65;
  a41=(a66*a41);
  a48=(a68*a48);
  a41=(a41+a48);
  a67=(a24*a67);
  a48=(a31*a67);
  a48=(a21*a48);
  a67=(a28*a67);
  a67=(a26*a67);
  a67=(a38*a67);
  a67=(a27*a67);
  a48=(a48+a67);
  a41=(a41-a48);
  if (res[1]!=0) res[1][53]=a41;
  a41=(a4*a68);
  a2=(a2*a41);
  a42=(a42*a66);
  a5=(a5*a42);
  a2=(a2-a5);
  a43=(a43*a66);
  a15=(a15*a43);
  a43=(a13*a68);
  a43=(a29*a43);
  a43=(a8*a43);
  a5=(a4*a43);
  a7=(a7*a5);
  a15=(a15+a7);
  a2=(a2-a15);
  a43=(a17*a43);
  a16=(a16*a43);
  a44=(a44*a66);
  a14=(a14*a44);
  a16=(a16-a14);
  a2=(a2-a16);
  a45=(a45*a66);
  a19=(a19*a45);
  a45=(a17*a68);
  a18=(a18*a45);
  a19=(a19+a18);
  a2=(a2-a19);
  a2=(a66*a2);
  a47=(a47*a66);
  a47=(a4*a47);
  a19=(a20*a68);
  a23=(a23*a19);
  a49=(a49*a23);
  a25=(a25*a49);
  a20=(a20*a25);
  a25=casadi_sq(a30);
  a22=(a22-a25);
  a22=(a27*a22);
  a25=(a26*a22);
  a49=(a28*a25);
  a23=(a31*a21);
  a49=(a49+a23);
  a49=(a24*a49);
  a20=(a20+a49);
  a47=(a47-a20);
  a50=(a50*a66);
  a4=(a4*a50);
  a52=(a52*a66);
  a52=(a17*a52);
  a4=(a4+a52);
  a8=(a8*a4);
  a29=(a29*a8);
  a13=(a13*a29);
  a47=(a47-a13);
  a1=(a1*a66);
  a17=(a17*a1);
  a47=(a47-a17);
  a47=(a68*a47);
  a2=(a2+a47);
  a25=(a36*a25);
  a24=(a24*a68);
  a31=(a31*a24);
  a25=(a25-a31);
  a25=(a21*a25);
  a36=(a36*a21);
  a28=(a28*a24);
  a36=(a36-a28);
  a26=(a26*a36);
  a38=(a38*a26);
  a30=(a30+a30);
  a30=(a30*a22);
  a39=(a39*a30);
  a38=(a38-a39);
  a27=(a27*a38);
  a25=(a25+a27);
  a2=(a2+a25);
  if (res[1]!=0) res[1][54]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int Solver_expl_ode_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Solver_expl_ode_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Solver_expl_ode_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Solver_expl_ode_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Solver_expl_ode_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Solver_expl_ode_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Solver_expl_ode_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Solver_expl_ode_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Solver_expl_ode_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int Solver_expl_ode_hess_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real Solver_expl_ode_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Solver_expl_ode_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Solver_expl_ode_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Solver_expl_ode_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s3;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Solver_expl_ode_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Solver_expl_ode_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
