/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Solver_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[59] = {7, 7, 0, 7, 14, 21, 28, 35, 42, 49, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s2[27] = {7, 3, 0, 7, 14, 21, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s3[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s4[26] = {22, 1, 0, 22, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21};

/* Solver_expl_vde_forw:(i0[7],i1[7x7],i2[7x3],i3[3],i4[22])->(o0[7],o1[7x7],o2[7x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][3] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a3=(a0*a2);
  a4=9.4500000000000001e-02;
  a5=3.8302866000000002e-01;
  a6=-1.2053807000000001e+00;
  a7=arg[3]? arg[3][1] : 0;
  a8=8.7391860000000002e-02;
  a7=(a7-a8);
  a7=(a6*a7);
  a7=tanh(a7);
  a8=(a5*a7);
  a9=tan(a8);
  a10=(a0*a9);
  a11=1.7499999999999999e-01;
  a10=(a10/a11);
  a11=(a4*a10);
  a12=sin(a1);
  a13=(a11*a12);
  a3=(a3-a13);
  if (res[0]!=0) res[0][0]=a3;
  a3=sin(a1);
  a13=(a0*a3);
  a14=cos(a1);
  a15=(a11*a14);
  a13=(a13+a15);
  if (res[0]!=0) res[0][1]=a13;
  if (res[0]!=0) res[0][2]=a10;
  a10=2.8887779235839844e+01;
  a13=5.9861721992492676e+00;
  a15=(a13*a0);
  a10=(a10-a15);
  a15=5.0000000000000000e-01;
  a16=100.;
  a17=arg[3]? arg[3][2] : 0;
  a18=-1.5045104920864105e-01;
  a19=(a17+a18);
  a19=(a16*a19);
  a19=tanh(a19);
  a20=1.;
  a21=(a19+a20);
  a21=(a15*a21);
  a22=(a10*a21);
  a17=(a17+a18);
  a18=(a22*a17);
  a23=-1.7194761037826538e+00;
  a24=1.3312559127807617e+01;
  a25=(a24*a0);
  a25=tanh(a25);
  a26=(a23*a25);
  a27=2.8984865546226501e-01;
  a28=(a27*a0);
  a26=(a26-a28);
  a18=(a18+a26);
  a26=1.6759805999999999e+00;
  a18=(a18/a26);
  if (res[0]!=0) res[0][3]=a18;
  a18=0.;
  if (res[0]!=0) res[0][4]=a18;
  if (res[0]!=0) res[0][5]=a18;
  if (res[0]!=0) res[0][6]=a0;
  a26=arg[1]? arg[1][3] : 0;
  a28=(a2*a26);
  a29=sin(a1);
  a30=arg[1]? arg[1][2] : 0;
  a31=(a29*a30);
  a31=(a0*a31);
  a28=(a28-a31);
  a31=5.7142857142857144e+00;
  a32=(a9*a26);
  a32=(a31*a32);
  a33=(a4*a32);
  a34=(a12*a33);
  a35=cos(a1);
  a36=(a35*a30);
  a36=(a11*a36);
  a34=(a34+a36);
  a28=(a28-a34);
  if (res[1]!=0) res[1][0]=a28;
  a28=(a3*a26);
  a34=cos(a1);
  a36=(a34*a30);
  a36=(a0*a36);
  a28=(a28+a36);
  a33=(a14*a33);
  a36=sin(a1);
  a30=(a36*a30);
  a30=(a11*a30);
  a33=(a33-a30);
  a28=(a28+a33);
  if (res[1]!=0) res[1][1]=a28;
  if (res[1]!=0) res[1][2]=a32;
  a32=5.9666561772851068e-01;
  a28=casadi_sq(a25);
  a28=(a20-a28);
  a33=(a24*a26);
  a33=(a28*a33);
  a33=(a23*a33);
  a30=(a27*a26);
  a33=(a33-a30);
  a30=(a13*a26);
  a30=(a21*a30);
  a30=(a17*a30);
  a33=(a33-a30);
  a33=(a32*a33);
  if (res[1]!=0) res[1][3]=a33;
  if (res[1]!=0) res[1][4]=a18;
  if (res[1]!=0) res[1][5]=a18;
  if (res[1]!=0) res[1][6]=a26;
  a26=arg[1]? arg[1][10] : 0;
  a33=(a2*a26);
  a30=arg[1]? arg[1][9] : 0;
  a37=(a29*a30);
  a37=(a0*a37);
  a33=(a33-a37);
  a37=(a9*a26);
  a37=(a31*a37);
  a38=(a4*a37);
  a39=(a12*a38);
  a40=(a35*a30);
  a40=(a11*a40);
  a39=(a39+a40);
  a33=(a33-a39);
  if (res[1]!=0) res[1][7]=a33;
  a33=(a3*a26);
  a39=(a34*a30);
  a39=(a0*a39);
  a33=(a33+a39);
  a38=(a14*a38);
  a30=(a36*a30);
  a30=(a11*a30);
  a38=(a38-a30);
  a33=(a33+a38);
  if (res[1]!=0) res[1][8]=a33;
  if (res[1]!=0) res[1][9]=a37;
  a37=(a24*a26);
  a37=(a28*a37);
  a37=(a23*a37);
  a33=(a27*a26);
  a37=(a37-a33);
  a33=(a13*a26);
  a33=(a21*a33);
  a33=(a17*a33);
  a37=(a37-a33);
  a37=(a32*a37);
  if (res[1]!=0) res[1][10]=a37;
  if (res[1]!=0) res[1][11]=a18;
  if (res[1]!=0) res[1][12]=a18;
  if (res[1]!=0) res[1][13]=a26;
  a26=arg[1]? arg[1][17] : 0;
  a37=(a2*a26);
  a33=arg[1]? arg[1][16] : 0;
  a38=(a29*a33);
  a38=(a0*a38);
  a37=(a37-a38);
  a38=(a9*a26);
  a38=(a31*a38);
  a30=(a4*a38);
  a39=(a12*a30);
  a40=(a35*a33);
  a40=(a11*a40);
  a39=(a39+a40);
  a37=(a37-a39);
  if (res[1]!=0) res[1][14]=a37;
  a37=(a3*a26);
  a39=(a34*a33);
  a39=(a0*a39);
  a37=(a37+a39);
  a30=(a14*a30);
  a33=(a36*a33);
  a33=(a11*a33);
  a30=(a30-a33);
  a37=(a37+a30);
  if (res[1]!=0) res[1][15]=a37;
  if (res[1]!=0) res[1][16]=a38;
  a38=(a24*a26);
  a38=(a28*a38);
  a38=(a23*a38);
  a37=(a27*a26);
  a38=(a38-a37);
  a37=(a13*a26);
  a37=(a21*a37);
  a37=(a17*a37);
  a38=(a38-a37);
  a38=(a32*a38);
  if (res[1]!=0) res[1][17]=a38;
  if (res[1]!=0) res[1][18]=a18;
  if (res[1]!=0) res[1][19]=a18;
  if (res[1]!=0) res[1][20]=a26;
  a26=arg[1]? arg[1][24] : 0;
  a38=(a2*a26);
  a37=arg[1]? arg[1][23] : 0;
  a30=(a29*a37);
  a30=(a0*a30);
  a38=(a38-a30);
  a30=(a9*a26);
  a30=(a31*a30);
  a33=(a4*a30);
  a39=(a12*a33);
  a40=(a35*a37);
  a40=(a11*a40);
  a39=(a39+a40);
  a38=(a38-a39);
  if (res[1]!=0) res[1][21]=a38;
  a38=(a3*a26);
  a39=(a34*a37);
  a39=(a0*a39);
  a38=(a38+a39);
  a33=(a14*a33);
  a37=(a36*a37);
  a37=(a11*a37);
  a33=(a33-a37);
  a38=(a38+a33);
  if (res[1]!=0) res[1][22]=a38;
  if (res[1]!=0) res[1][23]=a30;
  a30=(a24*a26);
  a30=(a28*a30);
  a30=(a23*a30);
  a38=(a27*a26);
  a30=(a30-a38);
  a38=(a13*a26);
  a38=(a21*a38);
  a38=(a17*a38);
  a30=(a30-a38);
  a30=(a32*a30);
  if (res[1]!=0) res[1][24]=a30;
  if (res[1]!=0) res[1][25]=a18;
  if (res[1]!=0) res[1][26]=a18;
  if (res[1]!=0) res[1][27]=a26;
  a26=arg[1]? arg[1][31] : 0;
  a30=(a2*a26);
  a38=arg[1]? arg[1][30] : 0;
  a33=(a29*a38);
  a33=(a0*a33);
  a30=(a30-a33);
  a33=(a9*a26);
  a33=(a31*a33);
  a37=(a4*a33);
  a39=(a12*a37);
  a40=(a35*a38);
  a40=(a11*a40);
  a39=(a39+a40);
  a30=(a30-a39);
  if (res[1]!=0) res[1][28]=a30;
  a30=(a3*a26);
  a39=(a34*a38);
  a39=(a0*a39);
  a30=(a30+a39);
  a37=(a14*a37);
  a38=(a36*a38);
  a38=(a11*a38);
  a37=(a37-a38);
  a30=(a30+a37);
  if (res[1]!=0) res[1][29]=a30;
  if (res[1]!=0) res[1][30]=a33;
  a33=(a24*a26);
  a33=(a28*a33);
  a33=(a23*a33);
  a30=(a27*a26);
  a33=(a33-a30);
  a30=(a13*a26);
  a30=(a21*a30);
  a30=(a17*a30);
  a33=(a33-a30);
  a33=(a32*a33);
  if (res[1]!=0) res[1][31]=a33;
  if (res[1]!=0) res[1][32]=a18;
  if (res[1]!=0) res[1][33]=a18;
  if (res[1]!=0) res[1][34]=a26;
  a26=arg[1]? arg[1][38] : 0;
  a33=(a2*a26);
  a30=arg[1]? arg[1][37] : 0;
  a37=(a29*a30);
  a37=(a0*a37);
  a33=(a33-a37);
  a37=(a9*a26);
  a37=(a31*a37);
  a38=(a4*a37);
  a39=(a12*a38);
  a40=(a35*a30);
  a40=(a11*a40);
  a39=(a39+a40);
  a33=(a33-a39);
  if (res[1]!=0) res[1][35]=a33;
  a33=(a3*a26);
  a39=(a34*a30);
  a39=(a0*a39);
  a33=(a33+a39);
  a38=(a14*a38);
  a30=(a36*a30);
  a30=(a11*a30);
  a38=(a38-a30);
  a33=(a33+a38);
  if (res[1]!=0) res[1][36]=a33;
  if (res[1]!=0) res[1][37]=a37;
  a37=(a24*a26);
  a37=(a28*a37);
  a37=(a23*a37);
  a33=(a27*a26);
  a37=(a37-a33);
  a33=(a13*a26);
  a33=(a21*a33);
  a33=(a17*a33);
  a37=(a37-a33);
  a37=(a32*a37);
  if (res[1]!=0) res[1][38]=a37;
  if (res[1]!=0) res[1][39]=a18;
  if (res[1]!=0) res[1][40]=a18;
  if (res[1]!=0) res[1][41]=a26;
  a26=arg[1]? arg[1][45] : 0;
  a37=(a2*a26);
  a33=arg[1]? arg[1][44] : 0;
  a29=(a29*a33);
  a29=(a0*a29);
  a37=(a37-a29);
  a29=(a9*a26);
  a29=(a31*a29);
  a38=(a4*a29);
  a30=(a12*a38);
  a35=(a35*a33);
  a35=(a11*a35);
  a30=(a30+a35);
  a37=(a37-a30);
  if (res[1]!=0) res[1][42]=a37;
  a37=(a3*a26);
  a34=(a34*a33);
  a34=(a0*a34);
  a37=(a37+a34);
  a38=(a14*a38);
  a36=(a36*a33);
  a36=(a11*a36);
  a38=(a38-a36);
  a37=(a37+a38);
  if (res[1]!=0) res[1][43]=a37;
  if (res[1]!=0) res[1][44]=a29;
  a29=(a24*a26);
  a28=(a28*a29);
  a28=(a23*a28);
  a29=(a27*a26);
  a28=(a28-a29);
  a29=(a13*a26);
  a29=(a21*a29);
  a29=(a17*a29);
  a28=(a28-a29);
  a28=(a32*a28);
  if (res[1]!=0) res[1][45]=a28;
  if (res[1]!=0) res[1][46]=a18;
  if (res[1]!=0) res[1][47]=a18;
  if (res[1]!=0) res[1][48]=a26;
  a26=arg[2]? arg[2][3] : 0;
  a28=(a2*a26);
  a29=sin(a1);
  a37=arg[2]? arg[2][2] : 0;
  a38=(a29*a37);
  a38=(a0*a38);
  a28=(a28-a38);
  a38=(a9*a26);
  a38=(a31*a38);
  a36=(a4*a38);
  a33=(a12*a36);
  a34=cos(a1);
  a30=(a34*a37);
  a30=(a11*a30);
  a33=(a33+a30);
  a28=(a28-a33);
  if (res[2]!=0) res[2][0]=a28;
  a28=(a3*a26);
  a33=cos(a1);
  a30=(a33*a37);
  a30=(a0*a30);
  a28=(a28+a30);
  a36=(a14*a36);
  a1=sin(a1);
  a37=(a1*a37);
  a37=(a11*a37);
  a36=(a36-a37);
  a28=(a28+a36);
  if (res[2]!=0) res[2][1]=a28;
  if (res[2]!=0) res[2][2]=a38;
  a25=casadi_sq(a25);
  a25=(a20-a25);
  a38=(a24*a26);
  a38=(a25*a38);
  a38=(a23*a38);
  a28=(a27*a26);
  a38=(a38-a28);
  a28=(a13*a26);
  a28=(a21*a28);
  a28=(a17*a28);
  a38=(a38-a28);
  a38=(a32*a38);
  if (res[2]!=0) res[2][3]=a38;
  if (res[2]!=0) res[2][4]=a18;
  if (res[2]!=0) res[2][5]=a18;
  if (res[2]!=0) res[2][6]=a26;
  a26=arg[2]? arg[2][10] : 0;
  a38=(a2*a26);
  a28=arg[2]? arg[2][9] : 0;
  a36=(a29*a28);
  a36=(a0*a36);
  a38=(a38-a36);
  a36=(a9*a26);
  a36=(a31*a36);
  a37=(a4*a36);
  a30=(a12*a37);
  a35=(a34*a28);
  a35=(a11*a35);
  a30=(a30+a35);
  a38=(a38-a30);
  a7=casadi_sq(a7);
  a7=(a20-a7);
  a6=(a6*a7);
  a5=(a5*a6);
  a8=cos(a8);
  a8=casadi_sq(a8);
  a5=(a5/a8);
  a5=(a0*a5);
  a5=(a31*a5);
  a8=(a4*a5);
  a6=(a12*a8);
  a38=(a38-a6);
  if (res[2]!=0) res[2][7]=a38;
  a8=(a14*a8);
  a38=(a3*a26);
  a6=(a33*a28);
  a6=(a0*a6);
  a38=(a38+a6);
  a37=(a14*a37);
  a28=(a1*a28);
  a28=(a11*a28);
  a37=(a37-a28);
  a38=(a38+a37);
  a8=(a8+a38);
  if (res[2]!=0) res[2][8]=a8;
  a5=(a5+a36);
  if (res[2]!=0) res[2][9]=a5;
  a5=(a24*a26);
  a5=(a25*a5);
  a5=(a23*a5);
  a36=(a27*a26);
  a5=(a5-a36);
  a36=(a13*a26);
  a36=(a21*a36);
  a36=(a17*a36);
  a5=(a5-a36);
  a5=(a32*a5);
  if (res[2]!=0) res[2][10]=a5;
  if (res[2]!=0) res[2][11]=a18;
  if (res[2]!=0) res[2][12]=a18;
  if (res[2]!=0) res[2][13]=a26;
  a26=arg[2]? arg[2][17] : 0;
  a2=(a2*a26);
  a5=arg[2]? arg[2][16] : 0;
  a29=(a29*a5);
  a29=(a0*a29);
  a2=(a2-a29);
  a9=(a9*a26);
  a31=(a31*a9);
  a4=(a4*a31);
  a12=(a12*a4);
  a34=(a34*a5);
  a34=(a11*a34);
  a12=(a12+a34);
  a2=(a2-a12);
  if (res[2]!=0) res[2][14]=a2;
  a3=(a3*a26);
  a33=(a33*a5);
  a0=(a0*a33);
  a3=(a3+a0);
  a14=(a14*a4);
  a1=(a1*a5);
  a11=(a11*a1);
  a14=(a14-a11);
  a3=(a3+a14);
  if (res[2]!=0) res[2][15]=a3;
  if (res[2]!=0) res[2][16]=a31;
  a19=casadi_sq(a19);
  a20=(a20-a19);
  a16=(a16*a20);
  a15=(a15*a16);
  a10=(a10*a15);
  a10=(a17*a10);
  a10=(a10+a22);
  a10=(a32*a10);
  a24=(a24*a26);
  a25=(a25*a24);
  a23=(a23*a25);
  a27=(a27*a26);
  a23=(a23-a27);
  a13=(a13*a26);
  a21=(a21*a13);
  a17=(a17*a21);
  a23=(a23-a17);
  a32=(a32*a23);
  a10=(a10+a32);
  if (res[2]!=0) res[2][17]=a10;
  if (res[2]!=0) res[2][18]=a18;
  if (res[2]!=0) res[2][19]=a18;
  if (res[2]!=0) res[2][20]=a26;
  return 0;
}

CASADI_SYMBOL_EXPORT int Solver_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Solver_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Solver_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Solver_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Solver_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Solver_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Solver_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void Solver_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Solver_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int Solver_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real Solver_expl_vde_forw_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Solver_expl_vde_forw_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Solver_expl_vde_forw_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Solver_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Solver_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Solver_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
